### ISSUE TITLE
Data could not be refreshed because the remote server could not contacted

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-data-weather#94]
~19k endpoints from May 6th - May 13th reporting E000000037, Data could not be refreshed because the remote server could not contacted. If widgets.risevision.com can be opened as expected then weather component shouldn't have problems reaching proxy.risevision.com to retrieve weather.

**Comment by stulees** [comment]
@alanclayton My summary of the impact adding proxy.risevision.com to our network check in Viewer is [here](https://trello.com/c/Qt2eMHGo/8119-issue-94-data-could-not-be-refreshed-because-the-remote-server-could-not-contacted-2#comment-60afc23176a8d16163e04b9d). I think we can close the defect, let me know if you disagree. Thanks

**Comment by stulees** [comment]
@alanclayton Another followup summary [here](https://trello.com/c/Qt2eMHGo/8119-issue-94-data-could-not-be-refreshed-because-the-remote-server-could-not-contacted-2#comment-60b10ebcba6d922962f46b40), thanks.
